/*
 * Tests for the workflow JSON → Rhai compiler (flow / stations only).
 */

//node builtins and test
import nodeTest from "node:test";
import nodeAssert from "node:assert/strict";
import nodeFs from "node:fs";
import nodePath from "node:path";
import nodeOs from "node:os";
import nodeUrl from "node:url";

//compiler library
import compileMod from "../src/compile-workflow.js";

//paths relative to this test file
const here = nodePath.dirname(nodeUrl.fileURLToPath(import.meta.url));
const repoRoot = nodePath.resolve(here, "..");
const shoppingPack = nodePath.join(
  repoRoot,
  "examples",
  "example-office-shopping"
);
const shoppingPath = nodePath.join(shoppingPack, "workflow.json");
const issuesPack = nodePath.join(repoRoot, "examples", "example-birthday-issues");
const issuesPath = nodePath.join(issuesPack, "workflow.json");

//flagship pack example
nodeTest.test("compiles example-office-shopping pack as flow", function testShopping() {

  //variables
  let workflow = null; //parsed doc
  let result = null; //compile result

  //load example
  workflow = compileMod.readJsonFile(shoppingPath);

  //compile (pack base = pack directory)
  result = compileMod.compileWorkflow(workflow, {
    base: shoppingPack, //asset root
  });

  //identity
  nodeAssert.equal(result.name, "example-office-shopping");
  nodeAssert.equal(result.scriptType, "flow");
  nodeAssert.match(result.rhai, /\/\/ scriptType: flow/);

  //build-artifact banner (analysis only; not for editing)
  nodeAssert.match(result.rhai, /BUILD ARTIFACT/);
  nodeAssert.match(result.rhai, /Suitable for analysis and debugging only/);
  nodeAssert.match(result.rhai, /Do not edit this file/);

  //human guide emitted in same compile cycle (always workflow.md content)
  nodeAssert.equal(typeof result.workflowMd, "string");
  nodeAssert.match(result.workflowMd, /BUILD ARTIFACT/);
  nodeAssert.match(result.workflowMd, /# example-office-shopping/);
  nodeAssert.match(result.workflowMd, /\/workflow example-office-shopping/);
  nodeAssert.match(result.workflowMd, /requests_dir/);
  nodeAssert.match(result.workflowMd, /\*\*Intake\*\*/);
  nodeAssert.match(result.workflowMd, /\*\*Purchasing\*\*/);

  //meta header present
  nodeAssert.match(result.rhai, /let meta = #\{/);
  nodeAssert.match(result.rhai, /name: "example-office-shopping"/);

  //station schemas loaded as locals (one binding per station) + payload envelope
  nodeAssert.match(result.rhai, /let intake_schema = #\{/);
  nodeAssert.match(result.rhai, /let inventory_schema = #\{/);
  nodeAssert.match(result.rhai, /let audit_schema = #\{/);
  nodeAssert.match(result.rhai, /let procurement_schema = #\{/);
  nodeAssert.match(result.rhai, /let purchasing_schema = #\{/);
  nodeAssert.match(result.rhai, /fn make_flow_schema/);

  //default requests_dir for host pack layout
  nodeAssert.match(result.rhai, /requests_dir/);

  //usage bookkeeping helpers (host tokens_used / duration_ms → flow.state)
  nodeAssert.match(result.rhai, /fn ensure_usage_state\(/);
  nodeAssert.match(result.rhai, /fn begin_station_visit\(/);
  nodeAssert.match(result.rhai, /fn record_usage_from_agent\(/);
  nodeAssert.match(result.rhai, /fn apply_agent_result\(/);
  nodeAssert.match(result.rhai, /token_total/);
  nodeAssert.match(result.rhai, /elapsed_total/);
  nodeAssert.match(result.rhai, /station_run/);
  nodeAssert.match(result.rhai, /tokens_used/);
  nodeAssert.match(result.rhai, /duration_ms/);

  //stations as functions + driver
  nodeAssert.match(result.rhai, /fn Intake\(/);
  nodeAssert.match(result.rhai, /fn Inventory\(/);
  nodeAssert.match(result.rhai, /fn Audit\(/);
  nodeAssert.match(result.rhai, /fn Procurement\(/);
  nodeAssert.match(result.rhai, /fn Purchasing\(/);
  nodeAssert.match(result.rhai, /phase\("Intake"\)/);
  nodeAssert.match(result.rhai, /phase\("Inventory"\)/);
  nodeAssert.match(result.rhai, /phase\("Audit"\)/);
  nodeAssert.match(result.rhai, /phase\("Procurement"\)/);
  nodeAssert.match(result.rhai, /phase\("Purchasing"\)/);
  nodeAssert.match(result.rhai, /while flow\.next != \(\)/);
  nodeAssert.match(result.rhai, /Fn\(flow\.next\)\.call/);
  nodeAssert.match(result.rhai, /capability_mode: "execute"/);

  //prompt banners (binding file basenames)
  nodeAssert.match(result.rhai, /===== \[common\.md\] =====/);
  nodeAssert.match(result.rhai, /===== \[intake\.md\] =====/);
  nodeAssert.match(result.rhai, /===== \[inventory\.md\] =====/);
  nodeAssert.match(result.rhai, /===== \[audit\.md\] =====/);
  nodeAssert.match(result.rhai, /===== \[procurement\.md\] =====/);
  nodeAssert.match(result.rhai, /===== \[purchasing\.md\] =====/);

  //no legacy step IR (host parallel / zip_filter ops)
  nodeAssert.doesNotMatch(result.rhai, /let inventory_results = parallel\(/);
  nodeAssert.doesNotMatch(result.rhai, /fn zip_filter|zip_filter\(/);

//end testShopping
});

//issues birthday pack (curated-corpus flow)
nodeTest.test("compiles example-birthday-issues pack as flow", function testIssues() {

  //variables
  let workflow = null; //doc
  let result = null; //compile

  workflow = compileMod.readJsonFile(issuesPath);
  result = compileMod.compileWorkflow(workflow, {
    base: issuesPack,
  });

  nodeAssert.equal(result.name, "example-birthday-issues");
  nodeAssert.match(result.rhai, /fn Intake\(/);
  nodeAssert.match(result.rhai, /fn Formulation\(/);
  nodeAssert.match(result.rhai, /fn Validation\(/);
  nodeAssert.match(result.rhai, /fn Presentation\(/);
  nodeAssert.match(result.rhai, /fn QA\(/);
  nodeAssert.match(result.rhai, /let intake_schema = #\{/);
  nodeAssert.match(result.rhai, /let formulation_schema = #\{/);
  nodeAssert.match(result.rhai, /let validation_schema = #\{/);
  nodeAssert.match(result.rhai, /let presentation_schema = #\{/);
  nodeAssert.match(result.rhai, /let qa_schema = #\{/);
  nodeAssert.match(result.rhai, /===== \[formulation\.md\] =====/);
  nodeAssert.match(result.workflowMd, /\/workflow example-birthday-issues/);

//end testIssues
});

//minimal stations array → phases + fns + next driver
nodeTest.test("compiles stations array to flow IR", function testFlowStations() {

  //variables
  let tmpDir = ""; //temp asset base
  let promptsDir = ""; //prompts dir
  let schemasDir = ""; //schemas dir
  let workflow = null; //flow doc
  let result = null; //compile result

  //temp base with two prompt files + one schema
  tmpDir = nodeFs.mkdtempSync(nodePath.join(nodeOs.tmpdir(), "wfflow-"));
  promptsDir = nodePath.join(tmpDir, "prompts");
  schemasDir = nodePath.join(tmpDir, "schemas");
  nodeFs.mkdirSync(promptsDir, { recursive: true });
  nodeFs.mkdirSync(schemasDir, { recursive: true });
  nodeFs.writeFileSync(
    nodePath.join(promptsDir, "a.md"),
    "Station A body\n",
    "utf8"
  );
  nodeFs.writeFileSync(
    nodePath.join(promptsDir, "b.md"),
    "Station B body\n",
    "utf8"
  );
  nodeFs.writeFileSync(
    nodePath.join(schemasDir, "widget.schema.json"),
    JSON.stringify({ type: "object", properties: { x: { type: "string" } } }),
    "utf8"
  );

  try {

    //two stations
    workflow = {
      name: "flow-demo", //name
      description: "minimal flow", //desc
      schemas: {
        widget: "widget.schema.json", //guidance
      },
      stations: [
        {
          name: "Alpha", //station
          prompt: ["a.md"], //path
          schemas: ["widget"], //guidance
        },
        {
          name: "Beta", //station
          prompt: ["b.md"], //path
          uiDescription: "second phase", //detail
        },
      ],
    };

    //compile
    result = compileMod.compileWorkflow(workflow, {
      base: tmpDir, //base
    });

    //flow IR markers
    nodeAssert.equal(result.scriptType, "flow");
    nodeAssert.match(result.rhai, /fn Alpha\(/);
    nodeAssert.match(result.rhai, /fn Beta\(/);
    nodeAssert.match(result.rhai, /===== \[a\.md\] =====/);
    nodeAssert.match(result.rhai, /===== \[b\.md\] =====/);
    nodeAssert.match(result.rhai, /title: "Alpha"/);
    nodeAssert.match(result.rhai, /title: "Beta"/);
    nodeAssert.match(result.rhai, /detail: "second phase"/);
    nodeAssert.match(result.rhai, /while flow\.next != \(\)/);

  } finally {

    //cleanup
    nodeFs.rmSync(tmpDir, { recursive: true, force: true });

  //end try
  }

//end testFlowStations
});

//prompts registry merges common + station bindings
nodeTest.test("flow prompts registry merges common + station bindings", function testPromptsRegistry() {

  //variables
  let tmpDir = ""; //temp
  let promptsDir = ""; //prompts
  let workflow = null; //doc
  let result = null; //compile

  tmpDir = nodeFs.mkdtempSync(nodePath.join(nodeOs.tmpdir(), "wfpreg-"));
  promptsDir = nodePath.join(tmpDir, "prompts");
  nodeFs.mkdirSync(nodePath.join(promptsDir, "stations"), { recursive: true });
  nodeFs.writeFileSync(
    nodePath.join(promptsDir, "stations", "common.md"),
    "COMMON\n",
    "utf8"
  );
  nodeFs.writeFileSync(
    nodePath.join(promptsDir, "stations", "a.md"),
    "A\n",
    "utf8"
  );

  try {

    workflow = {
      name: "preg-demo", //name
      description: "prompts registry", //desc
      prompts: {
        flow_common: "stations/common.md", //common
        station_a: "stations/a.md", //station
      },
      stations: [
        {
          name: "A", //name
          prompt: ["flow_common", "station_a"], //bindings
        },
      ],
    };

    result = compileMod.compileWorkflow(workflow, {
      base: tmpDir, //base
    });

    nodeAssert.match(result.rhai, /===== \[common\.md\] =====/);
    nodeAssert.match(result.rhai, /===== \[a\.md\] =====/);
    nodeAssert.match(result.rhai, /COMMON/);

  } finally {

    nodeFs.rmSync(tmpDir, { recursive: true, force: true });

  //end try
  }

//end testPromptsRegistry
});

//unknown prompt binding fails closed
nodeTest.test("unknown prompts binding fails closed", function testUnknownPromptBinding() {

  //variables
  let tmpDir = ""; //temp
  let promptsDir = ""; //prompts

  tmpDir = nodeFs.mkdtempSync(nodePath.join(nodeOs.tmpdir(), "wfpub-"));
  promptsDir = nodePath.join(tmpDir, "prompts");
  nodeFs.mkdirSync(promptsDir, { recursive: true });
  nodeFs.writeFileSync(nodePath.join(promptsDir, "a.md"), "A\n", "utf8");

  try {

    nodeAssert.throws(function runCompile() {

      compileMod.compileWorkflow(
        {
          name: "bad-prompt", //name
          description: "missing binding", //desc
          prompts: {
            flow_common: "stations/common.md", //missing file ok until used
          },
          stations: [
            {
              name: "A", //name
              prompt: ["nope"], //unknown binding
            },
          ],
        },
        { base: tmpDir }
      );

    //end run
    }, /was not declared in workflow\.prompts/);

  } finally {

    nodeFs.rmSync(tmpDir, { recursive: true, force: true });

  //end try
  }

//end testUnknownPromptBinding
});

//payloadSchema inlines $ref into envelope
nodeTest.test("flow payloadSchema inlines $ref into envelope", function testPayloadSchema() {

  //variables
  let tmpDir = ""; //temp
  let promptsDir = ""; //prompts
  let schemasDir = ""; //schemas
  let result = null; //compile

  tmpDir = nodeFs.mkdtempSync(nodePath.join(nodeOs.tmpdir(), "wfpay-"));
  promptsDir = nodePath.join(tmpDir, "prompts");
  schemasDir = nodePath.join(tmpDir, "schemas");
  nodeFs.mkdirSync(promptsDir, { recursive: true });
  nodeFs.mkdirSync(schemasDir, { recursive: true });
  nodeFs.writeFileSync(nodePath.join(promptsDir, "a.md"), "A\n", "utf8");
  nodeFs.writeFileSync(
    nodePath.join(schemasDir, "part.schema.json"),
    JSON.stringify({ type: "object", properties: { z: { type: "number" } } }),
    "utf8"
  );
  nodeFs.writeFileSync(
    nodePath.join(schemasDir, "payload.schema.json"),
    JSON.stringify({
      type: "object",
      properties: {
        nested: { $ref: "part.schema.json" },
      },
    }),
    "utf8"
  );

  try {

    result = compileMod.compileWorkflow(
      {
        name: "pay-demo", //name
        description: "payload inline", //desc
        payloadSchema: "payload.schema.json", //payload
        stations: [{ name: "A", prompt: ["a.md"] }],
      },
      { base: tmpDir }
    );

    //inlined nested property from $ref target (Rhai map key may be bare)
    nodeAssert.match(result.rhai, /\bz\b/);
    nodeAssert.match(result.rhai, /"type": "number"|type: "number"/);
    nodeAssert.match(result.rhai, /make_flow_schema/);

  } finally {

    nodeFs.rmSync(tmpDir, { recursive: true, force: true });

  //end try
  }

//end testPayloadSchema
});

//unknown station schema binding fails
nodeTest.test("flow station schemas unknown binding fails closed", function testStationSchema() {

  //variables
  let tmpDir = ""; //temp
  let promptsDir = ""; //prompts

  tmpDir = nodeFs.mkdtempSync(nodePath.join(nodeOs.tmpdir(), "wfss-"));
  promptsDir = nodePath.join(tmpDir, "prompts");
  nodeFs.mkdirSync(promptsDir, { recursive: true });
  nodeFs.writeFileSync(nodePath.join(promptsDir, "a.md"), "A\n", "utf8");

  try {

    nodeAssert.throws(function runCompile() {

      compileMod.compileWorkflow(
        {
          name: "ss-demo", //name
          description: "bad schema binding", //desc
          stations: [
            {
              name: "A", //name
              prompt: ["a.md"], //prompt
              schemas: ["missing_binding"], //unknown
            },
          ],
        },
        { base: tmpDir }
      );

    //end run
    }, /schemas|binding|unknown/i);

  } finally {

    nodeFs.rmSync(tmpDir, { recursive: true, force: true });

  //end try
  }

//end testStationSchema
});

//step authoring rejected
nodeTest.test("rejects step scriptType and workflow.steps", function testRejectStep() {

  //variables
  let tmpDir = ""; //temp
  let promptsDir = ""; //prompts

  tmpDir = nodeFs.mkdtempSync(nodePath.join(nodeOs.tmpdir(), "wfstep-"));
  promptsDir = nodePath.join(tmpDir, "prompts");
  nodeFs.mkdirSync(promptsDir, { recursive: true });
  nodeFs.writeFileSync(nodePath.join(promptsDir, "a.md"), "A\n", "utf8");

  try {

    nodeAssert.throws(function runCompile() {

      compileMod.compileWorkflow(
        {
          name: "step-demo", //name
          description: "legacy step", //desc
          scriptType: "step", //removed
          steps: [{ op: "log", message: "x" }],
        },
        { base: tmpDir }
      );

    //end run
    }, /step.*removed|stations\[\]/i);

    nodeAssert.throws(function runCompileSteps() {

      compileMod.compileWorkflow(
        {
          name: "steps-demo", //name
          description: "has steps", //desc
          steps: [{ op: "log", message: "x" }],
        },
        { base: tmpDir }
      );

    //end run
    }, /workflow\.steps is not supported/);

    nodeAssert.throws(function runCompilePhases() {

      compileMod.compileWorkflow(
        {
          name: "phases-demo", //name
          description: "has phases", //desc
          phases: [{ title: "X" }],
          stations: [{ name: "A", prompt: ["a.md"] }],
        },
        { base: tmpDir }
      );

    //end run
    }, /phases is not supported/);

  } finally {

    nodeFs.rmSync(tmpDir, { recursive: true, force: true });

  //end try
  }

//end testRejectStep
});

//compileWorkflowFile writes output
nodeTest.test("compileWorkflowFile writes output", function testCompileFile() {

  //variables
  let outDir = ""; //temp out
  let outPath = ""; //file
  let result = null; //compile
  let text = ""; //written
  let mdBesideJson = ""; //workflow.md next to authoring JSON
  let mdText = ""; //guide body
  let packDir = ""; //pack-style out dir
  let packRhai = ""; //workflow.rhai
  let packMd = ""; //workflow.md beside IR

  outDir = nodeFs.mkdtempSync(nodePath.join(nodeOs.tmpdir(), "wfout-"));
  outPath = nodePath.join(outDir, "example-office-shopping.rhai");
  mdBesideJson = nodePath.join(shoppingPack, "workflow.md");

  try {

    result = compileMod.compileWorkflowFile(shoppingPath, {
      base: shoppingPack, //base
      outPath: outPath, //out
    });

    nodeAssert.equal(result.written, true);
    text = nodeFs.readFileSync(outPath, "utf8");
    nodeAssert.match(text, /fn Intake\(/);
    nodeAssert.match(text, /===== \[intake\.md\] =====/);

    //same cycle: workflow.md beside authoring JSON (always that name)
    nodeAssert.ok(nodeFs.existsSync(mdBesideJson));
    mdText = nodeFs.readFileSync(mdBesideJson, "utf8");
    nodeAssert.match(mdText, /BUILD ARTIFACT/);
    nodeAssert.match(mdText, /# example-office-shopping/);
    nodeAssert.ok(
      result.workflowMdPaths.some(function has(p) {

        //normalized match
        return nodePath.resolve(p) === nodePath.resolve(mdBesideJson);

      //end some
      })
    );

    //pack-style: -o …/workflow.rhai also writes workflow.md beside IR
    packDir = nodePath.join(outDir, "pack");
    packRhai = nodePath.join(packDir, "workflow.rhai");
    packMd = nodePath.join(packDir, "workflow.md");
    result = compileMod.compileWorkflowFile(shoppingPath, {
      base: shoppingPack,
      outPath: packRhai,
    });
    nodeAssert.ok(nodeFs.existsSync(packRhai));
    nodeAssert.ok(nodeFs.existsSync(packMd));
    nodeAssert.match(
      nodeFs.readFileSync(packMd, "utf8"),
      /\/workflow example-office-shopping/
    );

  } finally {

    nodeFs.rmSync(outDir, { recursive: true, force: true });

  //end try
  }

//end testCompileFile
});

//missing prompt file fails closed
nodeTest.test("rejects missing prompt file", function testMissingPrompt() {

  //variables
  let tmpDir = ""; //temp
  let promptsDir = ""; //prompts

  tmpDir = nodeFs.mkdtempSync(nodePath.join(nodeOs.tmpdir(), "wfmiss-"));
  promptsDir = nodePath.join(tmpDir, "prompts");
  nodeFs.mkdirSync(promptsDir, { recursive: true });

  try {

    nodeAssert.throws(function runCompile() {

      compileMod.compileWorkflow(
        {
          name: "miss", //name
          description: "missing prompt", //desc
          stations: [
            {
              name: "A", //name
              prompt: ["does-not-exist.md"], //missing
            },
          ],
        },
        { base: tmpDir }
      );

    //end run
    }, /failed to load prompt file/);

  } finally {

    nodeFs.rmSync(tmpDir, { recursive: true, force: true });

  //end try
  }

//end testMissingPrompt
});

//flat args defaults
nodeTest.test("binds args from flat default values", function testArgsFlatDefault() {

  //variables
  let tmpDir = ""; //temp
  let promptsDir = ""; //prompts
  let result = null; //compile

  tmpDir = nodeFs.mkdtempSync(nodePath.join(nodeOs.tmpdir(), "wfargs-"));
  promptsDir = nodePath.join(tmpDir, "prompts");
  nodeFs.mkdirSync(promptsDir, { recursive: true });
  nodeFs.writeFileSync(nodePath.join(promptsDir, "a.md"), "out={{args.out_dir}}\n", "utf8");

  try {

    result = compileMod.compileWorkflow(
      {
        name: "args-flat", //name
        description: "flat args", //desc
        args: {
          out_dir: "workflows/example-birthday-issues/output", //default
          requests_dir: true, //required
        },
        stations: [{ name: "A", prompt: ["a.md"] }],
      },
      { base: tmpDir }
    );

    nodeAssert.match(
      result.rhai,
      /let out_dir = if args == \(\) \|\| args\.out_dir == \(\) \{ "workflows\/example-birthday-issues\/output" \} else \{ args\.out_dir \};/
    );
    nodeAssert.match(result.rhai, /Pass args\.requests_dir/);

  } finally {

    nodeFs.rmSync(tmpDir, { recursive: true, force: true });

  //end try
  }

//end testArgsFlatDefault
});

//nested default rejected
nodeTest.test("rejects nested default under args", function testArgsLegacyDefault() {

  //variables
  let tmpDir = ""; //temp
  let promptsDir = ""; //prompts

  tmpDir = nodeFs.mkdtempSync(nodePath.join(nodeOs.tmpdir(), "wfleg-"));
  promptsDir = nodePath.join(tmpDir, "prompts");
  nodeFs.mkdirSync(promptsDir, { recursive: true });
  nodeFs.writeFileSync(nodePath.join(promptsDir, "a.md"), "A\n", "utf8");

  try {

    nodeAssert.throws(function runCompile() {

      compileMod.compileWorkflow(
        {
          name: "args-legacy", //name
          description: "legacy default", //desc
          args: {
            company_name: { default: "Acme Office" }, //legacy
          },
          stations: [{ name: "A", prompt: ["a.md"] }],
        },
        { base: tmpDir }
      );

    //end run
    }, /put the value directly after the key/);

  } finally {

    nodeFs.rmSync(tmpDir, { recursive: true, force: true });

  //end try
  }

//end testArgsLegacyDefault
});
